import sys
import glob
import os




str = """    spriteType = {
        name = GFX_goal_FILE_ID
        texturefile = gfx/interface/goals/FILE_PATH
    }
    spriteType = {
        name = GFX_goal_FILE_ID_shine
        texturefile = gfx/interface/goals/FILE_PATH
        effectFile = gfx/FX/buttonstate.lua
        animation = {
            animationmaskfile = gfx/interface/goals/FILE_PATH
            animationtexturefile = gfx/interface/goals/shine_overlay.dds
            animationrotation = -90.0
            animationlooping = no
            animationtime = 0.75
            animationdelay = 0
            animationblendmode = "add"
            animationtype = "scrolling"
            animationrotationoffset = { x = 0.0 y = 0.0 }
            animationtexturescale = { x = 1.0 y = 1.0 }
        }
        animation = {
            animationmaskfile = gfx/interface/goals/FILE_PATH
            animationtexturefile = gfx/interface/goals/shine_overlay.dds
            animationrotation = 90.0
            animationlooping = no
            animationtime = 0.75
            animationdelay = 0
            animationblendmode = "add"
            animationtype = "scrolling"
            animationrotationoffset = { x = 0.0 y = 0.0 }
            animationtexturescale = { x = 1.0 y = 1.0 }
        }
        legacy_lazy_load = no
    }
"""




print("spriteTypes = {")
print("\t# This file was auto-generated by goals_gfx.py")


for root, dirs, files in os.walk("../"):
	for file in files:
		if file.endswith(".dds"):
			file_id = file[0:len(file)-4]
			file_path = os.path.join(root[3:], file).replace('\\', '/')
			
			print(str.replace("FILE_ID", file_id).replace("FILE_PATH", file_path))


print("}")
exit(0)