import sys
import glob
import os




str = """    spriteType = {
        name = "GFX_FILE_ID"
        texturefile = "FILE_PATH"
    }
"""





print("spriteTypes = {")
print("\t# This file was auto-generated by GFX-Maker.py")


for root, dirs, files in os.walk("../../gfx/interface/military_industrial_organization/emblems"):
	for file in files:
		if file.endswith(".dds"):
			file_id = file[0:len(file)-4]
			file_path = os.path.join(root[6:], file).replace('\\', '/')
			
			print(str.replace("FILE_ID", file_id).replace("FILE_PATH", file_path))

for root, dirs, files in os.walk("../../gfx/interface/military_industrial_organization/policies"):
	for file in files:
		if file.endswith(".dds"):
			file_id = file[0:len(file)-4]
			file_path = os.path.join(root[6:], file).replace('\\', '/')
			
			print(str.replace("FILE_ID", file_id).replace("FILE_PATH", file_path))

for root, dirs, files in os.walk("../../gfx/interface/military_industrial_organization/traits"):
	for file in files:
		if file.endswith(".dds"):
			file_id = file[0:len(file)-4]
			file_path = os.path.join(root[6:], file).replace('\\', '/')
			
			print(str.replace("FILE_ID", file_id).replace("FILE_PATH", file_path))


print("}")
exit(0)