import sys
import glob
import os
from wand import image
from wand.color import Color

def apply_mask(img, mask):
    # 'activate' is the safer, modern Wand equivalent to setting it to True
    img.alpha_channel = 'activate'
    img.composite_channel("alpha", mask, "dst_in")

def apply_dropshadow(img):
    # Hard-coded parameters for drop-shadow effect
    shadow_color = Color('#000000')  # Black color
    shadow_opacity = Color('#808080')  # Opacity (0 to 1) for each color
    shadow_offset = (3, 3)  # Offset in (x, y) coordinates
    shadow_blur_radius = 2  # Radius of Gaussian blur

    # Create a new image with transparent background for shadow
    with image.Image(width=img.width, height=img.height, background=Color('transparent')) as shadow:
        # Draw the original image onto the shadow canvas with an offset
        shadow.composite(img)

        # Apply Gaussian blur to the shadow
        shadow.gaussian_blur(shadow_blur_radius, shadow_blur_radius)

        # Set shadow color and opacity
        shadow.colorize(shadow_color, shadow_opacity)

        # Composite the shadow and original image
        img.composite(shadow, left=shadow_offset[0], top=shadow_offset[1], operator='lighten')

def convert_image(img_file, out_path):
    # Using 'with' ensures the memory is freed after each image is processed
    with image.Image(filename='res/reportevents_mask.dds') as mask:
        with image.Image(filename=img_file) as img:
            
            # --- THE FIX ---
            # Force the image to 32-bit RGBA. This stops indexed/paletted PNGs
            # from turning completely black when processing the alpha mask and blur.
            img.type = 'truecoloralpha'

            # Apply alpha mask
            apply_mask(img, mask)

            # Apply drop shadow effect
            apply_dropshadow(img)

            # Only apply DXT5 compression if the output is a DDS file
            if out_path.lower().endswith('.dds'):
                img.compression = 'dxt5'
                
            img.save(filename=out_path)


print("spriteTypes = {")
print("\t# This file was auto-generated by the GFX-Maker.py")

# Fetch both .dds and .png files
image_files = glob.glob("../../gfx/event_pictures/report_events/unmasked/*.dds") + \
              glob.glob("../../gfx/event_pictures/report_events/unmasked/*.png")

for file in image_files:
    filename = os.path.basename(file)
    newfile = "../../gfx/event_pictures/report_events/" + filename
    convert_image(file, newfile)

    # Slices off the last 4 characters (".dds" or ".png") to get the ID
    gfx_id = str.lower(filename[0:len(filename)-4])
    print("\tspriteType = { name = \"GFX_"+gfx_id+"\" texturefile = \"gfx/event_pictures/report_events/"+filename+"\" }")

print("}")
exit(0)