import sys
import glob
import os




str = """    spriteType = {
        name = "GFX_idea_FILE_ID"
        texturefile = "gfx/interface/ideas/national_spirits/FILE_PATH"
    }
"""




print("spriteTypes = {")
print("\t# This file was auto-generated by gfx_spirits.py")


for root, dirs, files in os.walk("../"):
	for file in files:
		if file.endswith(".dds"):
			file_id = file[0:len(file)-4]
			file_path = os.path.join(root[3:], file).replace('\\', '/')
			
			print(str.replace("FILE_ID", file_id).replace("FILE_PATH", file_path))


print("}")
exit(0)