content_string = """

### Resolution: $NAME$

# Effect when resolution $NAME$ is passed
ea_resolution_$NAME$_effect = {

	if = {
		limit = { has_idea = ea_resolution_$NAME$_idea_1 }
		swap_ideas = { remove_idea = ea_resolution_$NAME$_idea_1 add_idea = ea_resolution_$NAME$_idea_2 }
	}
	else_if = {
		limit = { has_idea = ea_resolution_$NAME$_idea_2 }
		swap_ideas = { remove_idea = ea_resolution_$NAME$_idea_2 add_idea = ea_resolution_$NAME$_idea_3 }
	}
	else_if = {
		limit = { has_idea = ea_resolution_$NAME$_idea_3 }
		swap_ideas = { remove_idea = ea_resolution_$NAME$_idea_3 add_idea = ea_resolution_$NAME$_idea_4 }
	}
	else_if = {
		limit = { has_idea = ea_resolution_$NAME$_idea_4 }
		swap_ideas = { remove_idea = ea_resolution_$NAME$_idea_4 add_idea = ea_resolution_$NAME$_idea_5 }
	}
	else = {
		add_ideas = ea_resolution_$NAME$_idea_1
	}
}

# Tooltip of the currently active $NAME$ resolution
ea_resolution_$NAME$_current_tteffect = {

	custom_effect_tooltip = ea_resolution_current_tt

	if = {
		limit = { has_idea = ea_resolution_$NAME$_idea_1 }
		show_ideas_tooltip = ea_resolution_$NAME$_idea_1
	}
	else_if = {
		limit = { has_idea = ea_resolution_$NAME$_idea_2 }
		show_ideas_tooltip = ea_resolution_$NAME$_idea_2
	}
	else_if = {
		limit = { has_idea = ea_resolution_$NAME$_idea_3 }
		show_ideas_tooltip = ea_resolution_$NAME$_idea_3
	}
	else_if = {
		limit = { has_idea = ea_resolution_$NAME$_idea_4 }
		show_ideas_tooltip = ea_resolution_$NAME$_idea_4
	}
	else = {
		custom_effect_tooltip = ea_resolution_none_tt
	}
}

# Tooltip of the next tier $NAME$ resolution
ea_resolution_$NAME$_next_tteffect = {

	custom_effect_tooltip = ea_resolution_next_tt

	if = {
		limit = { has_idea = ea_resolution_$NAME$_idea_1 }
		show_ideas_tooltip = ea_resolution_$NAME$_idea_2
	}
	else_if = {
		limit = { has_idea = ea_resolution_$NAME$_idea_2 }
		show_ideas_tooltip = ea_resolution_$NAME$_idea_3
	}
	else_if = {
		limit = { has_idea = ea_resolution_$NAME$_idea_3 }
		show_ideas_tooltip = ea_resolution_$NAME$_idea_4
	}
	else = {
		add_ideas = ea_resolution_$NAME$_idea_1
	}
}

# Adds the current $NAME$ resolution to a country
ea_resolution_$NAME$_add_to_new_member = {

	any_country = {
		limit = { has_country_flag = is_elven_$NAME$_member }

		if = {
			limit = { has_idea = ea_resolution_$NAME$_idea_1 }
			ROOT = { add_ideas = ea_resolution_$NAME$_idea_1 }
		}
		else_if = {
			limit = { has_idea = ea_resolution_$NAME$_idea_2 }
			ROOT = { add_ideas = ea_resolution_$NAME$_idea_2 }
		}
		else_if = {
			limit = { has_idea = ea_resolution_$NAME$_idea_3 }
			ROOT = { add_ideas = ea_resolution_$NAME$_idea_3 }
		}
		else_if = {
			limit = { has_idea = ea_resolution_$NAME$_idea_4 }
			ROOT = { add_ideas = ea_resolution_$NAME$_idea_4 }
		}
		else_if = {
			limit = { has_idea = ea_resolution_$NAME$_idea_5 }
			ROOT = { add_ideas = ea_resolution_$NAME$_idea_5 }
		}
	}
}

"""



name_list = { "alliance", "industry", "expansion", "trade", "peace", "research", "hegemony", "martial", "union" }

print("# This file was generated by _generate_ea_resolutions.py")

for name in name_list:
    print(content_string.replace("$NAME$", name))